import { Home, Package, Compass, FileText, CreditCard, User, Bell } from 'lucide-react';

export const ACCOUNT_NAV_ITEMS = [
  {
    id: 'home',
    label: 'Home',
    href: '/',
    isHome: true,
    icon: Home,
  },
  {
    id: 'bookings',
    label: 'My Bookings',
    href: '/account/bookings',
    path: 'bookings',
    title: 'My Bookings',
    subtitle: 'View and manage your booked containers, track shipments, and access all related documents.',
    icon: Package,
  },
  {
    id: 'track',
    label: 'Track Shipment',
    href: '/account/track',
    path: 'track',
    title: 'Track Shipment',
    subtitle: 'Track your shipments in real time.',
    icon: Compass,
  },
  {
    id: 'documents',
    label: 'Documents',
    href: '/account/documents',
    path: 'documents',
    title: 'Documents',
    subtitle: 'Access and manage documents for your bookings.',
    icon: FileText,
  },
  {
    id: 'billing',
    label: 'Billing & Payments',
    href: '/account/billing',
    path: 'billing',
    title: 'Billing & Payments',
    subtitle: 'View invoices and payment history.',
    icon: CreditCard,
  },
  {
    id: 'profile',
    label: 'Profile Settings',
    href: '/account/profile',
    path: 'profile',
    title: 'Profile Settings',
    subtitle: 'Manage your account details and preferences.',
    icon: User,
  },
  {
    id: 'notifications',
    label: 'Notifications',
    href: '/account/notifications',
    path: 'notifications',
    title: 'Notifications',
    subtitle: 'Stay up to date with your shipments and bookings.',
    icon: Bell,
  },
];
